variables:
- group: 'ssh-connections'
 
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Gradle@2
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'build'

    - task: CmdLine@2
      inputs:
        script: ls -alh dist/
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/dist/trainSchedule.zip'
        artifact: 'trainSchedule.zip'
        publishLocation: 'pipeline'
  
- stage: Test
  jobs:
  - job: Testing
    steps:
    - task: Bash@3
      inputs:
          targetType: 'inline'
          script: |
            echo "Using the environment connection $env:SSH_CONNECTION"
      env:
        SSH_CONNECTION: $(id_rsa.pub)
        
- stage: Staging
  jobs:
  - job: CopyFilesOverSSHtoStaging
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'trainSchedule.zip'
        targetPath: '$(Pipeline.Workspace)/dist/'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'staging-server'
        sourceFolder: '$(Pipeline.Workspace)/dist/'
        contents: 'trainSchedule.zip'
        targetFolder: '/tmp'
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'staging-server'
        runOptions: 'inline'
        inline: 'sudo /usr/bin/systemctl stop train-schedule && rm -rf /opt/train-schedule/* && unzip /tmp/trainSchedule.zip -d /opt/train-schedule && sudo /usr/bin/systemctl start train-schedule'
        readyTimeout: '20000'

- stage: Production
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation - Staging OK?
    pool: server
    timeoutInMinutes: 4320
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: 
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
  
  - job: CopyFilesOverSSHtoProduction
    dependsOn: waitForValidation
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'trainSchedule.zip'
        targetPath: '$(Pipeline.Workspace)/dist/'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'production-server'
        sourceFolder: '$(Pipeline.Workspace)/dist/'
        contents: 'trainSchedule.zip'
        targetFolder: '/tmp'
        readyTimeout: '20000'
    - task: SSH@0
      inputs:
        sshEndpoint: 'production-server'
        runOptions: 'inline'
        inline: 'sudo /usr/bin/systemctl stop train-schedule && rm -rf /opt/train-schedule/* && unzip /tmp/trainSchedule.zip -d /opt/train-schedule && sudo /usr/bin/systemctl start train-schedule'
        readyTimeout: '20000'